### PR TITLE
Things for 2.0

### PR DESCRIPTION
**Pull request by Gradiella**
actually, i was lying it was all just bug fixes lol finnaly stable build

- [x] Update to discord.js v14
- [x] Adding a button that generates more seeds or whatever
- [x] Prevention for the bot to output the same seed in a row
- [x] submitable seeds
- [x] make button to show more seeds (for submitable seeds)

### CODE REVIEW

**Comment by Aeroshide** [comment]
lmao i thought it was gonna be crap / re-written in python.

so i want you to repolish the findseed too, i see that ctime has been repolished:

- [x] adding a button that generates more seeds or whatever
- [x] prevention for the bot to output the same seed in a row

**Comment by Gradiella** [comment]
Yeah, but we would have to update to discord.js v14, because buttons and slash commands are getting changed, i wouldn't mind using v13 but, I'm guessing neither of us is going to port the bot to v14 when its deprecated.

discord.js v14 is going to use Discord API v10, which has a lot of features we could expand this bot on.

So i probably would need a bit of help for this.. or not..

**Comment by Aeroshide** [comment]
Uh yeah this is pretty amazing, now we just need the seed submission system, and also have a command that would either spout the seed randomly or have them look through the list. figure out which ones better ¯\_(ツ)_/¯

**Comment by Aeroshide** [comment]
Also is the generate seed even possible? if it is, we should quit using the seedbank

**Comment by Gradiella** [comment]
> Also is the generate seed even possible? if it is, we should quit using the seedbank

Yeah, this is probably too complicated. but it might be possible

**Comment by Gradiella** [comment]
Also, i have done everything that is requested. Are we ready to merge now?

A few things that changed under the hood:
session token is completely solid now, there was a little bug that could crash the bot

yes session token is a complete game changer, you could review the system by yourself, it should be pretty simple to understand

**Comment by Aeroshide** [comment]
For real, i think we are ready to merge. ill do the extra work for making it work on my host (since i think your code was only tested in local environment).

Thanks for the helping hand!, the bot should be up and running again in a few days, and ready for early testing.

**Pull request merged**
